ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Controllers/mainHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using University_Registration.Models;

namespace University_Registration.Controllers
{
    public class mainHomeController : Controller
    {
        ERP_SystemEntities1 db = new ERP_SystemEntities1();

        // GET: mainHome
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public ActionResult EmailSubmit(string name,string email,string message,string subject)
        {
            MailMessage mail = new MailMessage();
            mail.To.Add("obidatm68@gmail.com");
            mail.From = new MailAddress(email);

            mail.Subject = email;
            mail.Body = "message";

            SmtpClient smtp = new SmtpClient();
            smtp.Port = 587;
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;
            smtp.Host = "smtp.gmail.com";
            smtp.Credentials = new System.Net.NetworkCredential("obidatm68@gmail.com", "zrwtqpllpsbviqws");
            smtp.Send(mail);
            return RedirectToAction("Contact");
        }

        public ActionResult coarses(int? id)
        {

            if (id == null)
            {
                var course = from m in db.Majors select m;
                return View(course);
            }
            else
            {
                var course = from m in db.Majors where m.Facility_ID == id select m;
                return View(course);
            }
            return View();
        }
        public ActionResult test()
        {
            return View();
        }
    }
}

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/mainHome/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}




<!-- Breadcrumb section -->
<div class="site-breadcrumb">
    <div class="container">
        <a href="#"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-right"></i>
        <span>About Us</span>
    </div>
</div>
<!-- Breadcrumb section end -->
<!-- About section -->
<section class="about-section spad pt-0">
    <div class="container">
        <div class="section-title text-center">
            <h3>WELCOME TO EZUCA</h3>
            <p>Let children creative and make a different</p>
        </div>
        <div class="row">
            <div class="col-lg-6 about-text">
                <h5>About us</h5>
                <p>Unica University is a prestigious institution of higher education dedicated to providing students with a well-rounded academic experience that prepares them for success in their chosen fields. Founded on the principles of academic excellence and innovation, Unica University is committed to fostering a culture of creativity, critical thinking, and lifelong learning.</p>
                <h5 class="pt-4">Our history</h5>
                
                <ul class="about-list">
                    <li><i class="fa fa-check-square-o"></i> University Faculties organise teaching and research into individual subjects.</li>
                    <li><i class="fa fa-check-square-o"></i> The University is rich in history - its famous buildings attract visitors.</li>
                    <li><i class="fa fa-check-square-o"></i> 50 years of people, and achievements that continue to transform.</li>
                    <li><i class="fa fa-check-square-o"></i> The University's core values are as follows:freedom of thought.</li>
                </ul>
            </div>
            <div class="col-lg-6 pt-5 pt-lg-0">
                <img src="~/Content/img/about.jpg" alt="">
             
            </div>
        </div>
    </div>
</section>
<!-- About section end-->
<!-- Testimonial section  -->
<section class="testimonial-section spad">
    <div class="container">
        <div class="testimonial-slider owl-carousel">
            <div class="ts-item">
                <div class="row">
                    <div class="col-md-3">
                        <div class="ts-author-pic set-bg" data-setbg="@Url.Content("~/Content/img/member/5.jpg")"></div>
                    </div>
                    <div class="col-md-9 ts-text">
                        <p>“ I want to let you know that I am very absolutely delighted with the course in every respect. It has been particularly pleasing for me, with an interest in seeing the application and good educational practice to school education. Learn a different approach that leads to better outcomes. ”</p>
                        <h5>Mr. Peter Crough</h5>
                        <span>Student’s Parent</span>
                    </div>
                </div>
            </div>
            <div class="ts-item">
                <div class="row">
                    <div class="col-md-3">
                        <div class="ts-author-pic set-bg" data-setbg="@Url.Content("~/Content/img/member/5.jpg")"></div>
                    </div>
                    <div class="col-md-9 ts-text">
                        <p>“ I want to let you know that I am very absolutely delighted with the course in every respect. It has been particularly pleasing for me, with an interest in seeing the application and good educational practice to school education. Learn a different approach that leads to better outcomes. ”</p>
                        <h5>Mr. Peter Crough</h5>
                        <span>Student’s Parent</span>
                    </div>
                </div>
            </div>
            <div class="ts-item">
                <div class="row">
                    <div class="col-md-3">
                        <div class="ts-author-pic set-bg" data-setbg="@Url.Content("~/Content/img/member/5.jpg")"></div>
                    </div>
                    <div class="col-md-9 ts-text">
                        <p>“ I want to let you know that I am very absolutely delighted with the course in every respect. It has been particularly pleasing for me, with an interest in seeing the application and good educational practice to school education. Learn a different approach that leads to better outcomes. ”</p>
                        <h5>Mr. Peter Crough</h5>
                        <span>Student’s Parent</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Testimonial section end -->
<!-- Team section  -->
<section class="team-section spad">
    <div class="container">
        <div class="section-title text-center">
            <h3>OUR TEAM</h3>
            <p>The professional standards and expectations</p>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-3">
                <div class="member">
                    <div class="member-pic set-bg" data-setbg="@Url.Content("~/Content/img/raghad.jpeg")">
                        <div class="member-social">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                    <h5>Raghad Alghoul</h5>
                    <p>Quality Assurance</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="member">
                    <div class="member-pic set-bg" data-setbg="@Url.Content("~/Content/img/lujain.jpeg")">
                        <div class="member-social">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                    <h5>Lujain Alnouti</h5>
                    <p>Producr Owner</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="member">
                    <div class="member-pic set-bg" data-setbg="@Url.Content("~/Content/img/mos.jpeg")">
                        <div class="member-social">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                    <h5>Mosab Ghannam</h5>
                    <p>Scrum Master</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="member">
                    <div class="member-pic set-bg" data-setbg="@Url.Content("~/Content/img/malik.jpeg")">
                        <div class="member-social">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                    <h5>Malik Obaidat</h5>
                    <p>Devloper</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="member">
                    <div class="member-pic set-bg" data-setbg="@Url.Content("~/Content/img/momen.jpeg")">
                        <div class="member-social">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                    <h5>Momen Abu alhaija</h5>
                    <p>Devloper</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="member">
                    <div class="member-pic set-bg" data-setbg="@Url.Content("~/Content/img/haya.jpeg")">
                        <div class="member-social">
                            <a href=""><i class="fa fa-facebook"></i></a>
                            <a href=""><i class="fa fa-twitter"></i></a>
                            <a href=""><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                    <h5>Haya Alkhateeb</h5>
                    <p>Devloper</p>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- Team section end -->

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/mainHome/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<!-- Breadcrumb section -->
<div class="site-breadcrumb">
    <div class="container">
        <a href="#"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-right"></i>
        <span>Contact</span>
    </div>
</div>
<!-- Breadcrumb section end -->
<!-- Courses section -->
<section class="contact-page spad pt-0">
    <div class="container">
        <div class="map-section">
            <div class="contact-info-warp">
                <div class="contact-info">
                    <h4>Address</h4>
                    <p>40 Baria Street 133/2, NewYork City, US</p>
                </div>
                <div class="contact-info">
                    <h4>Phone</h4>
                    <p>(+88) 111 555 666</p>
                </div>
                <div class="contact-info">
                    <h4>Email</h4>
                    <p>infodeercreative@gmail.com</p>
                </div>
                <div class="contact-info">
                    <h4>Working time</h4>
                    <p>Monday - Friday: 08 AM - 06 PM</p>
                </div>
            </div>
            <!-- Google map -->
            <div class="map" id="map-canvas"></div>
        </div>
        <div class="contact-form spad pb-0">
            <div class="section-title text-center">
                <h3>GET IN TOUCH</h3>
                <p>Contact us for best deals and offer</p>
            </div>

            @using (Html.BeginForm("EmailSubmit", "mainHome", FormMethod.Post, new { enctype = "multipart/form-data" , @class = "comment-form --contact" }))
            {
                <div class="row">
                    <div class="col-lg-4">
                        <input type="text" name="name" id="name" placeholder="Your Name">
                    </div>
                    <div class="col-lg-4">
                        <input type="text" name="email" id="email" placeholder="Your Email">
                    </div>
                    <div class="col-lg-4">
                        <input type="text" name="Subject" id="Subject" placeholder="Subject">
                    </div>
                    <div class="col-lg-12">
                        <textarea placeholder="Message" name="message" id="message"></textarea>
                        <div class="text-center">
                            <input type="submit" value="SUBMIT" class="site-btn" />
                        </div>
                    </div>
                </div>
                
                
                
                <br />
                <br />
            }
            
        </div>
    </div>
</section>
<!-- Courses section end-->
<!-- Newsletter section -->

<!-- load for map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB0YyDTa0qqOjIerob2VTIwo_XVMhrruxo"></script>
<script src="~/Scripts/js/map.js"></script>

<!-- Newsletter section end -->

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/mainHome/coarses.cshtml
@{
    ViewBag.Title = "coarses";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}
@model IEnumerable<University_Registration.Models.Major>



<!-- Breadcrumb section -->
<div class="site-breadcrumb">
    <div class="container">
        <a href="#"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-right"></i>
        <span>Courses</span>
    </div>
</div>
<!-- Breadcrumb section end -->
<!-- Courses section -->
<section class="full-courses-section spad pt-0">
    <div class="container">
        <a class="row" href="/Student/StudentDashBoard">
            @foreach (var item in Model)
            {
                
                <div class="col-lg-4 col-md-6 course-item">
                    <div class="course-thumb">
                        <img height="190px" width="300px" src="../../Images/@item.Major_Image" alt="">
                        <div class="course-cat">
                            <span>@item.Name</span>
                        </div>
                    </div>
                    <div class="course-info">
                        <h4>@item.Description</h4>
                        <h4 class="cource-price">@item.price<span>/One Hour</span></h4>
                    </div>

                </div>


            }

        </a>

    </div>
</section>
<!-- Courses section end-->

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/mainHome/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_loginLayout.cshtml";
}
<style>
    .wrap-input100 {
      height: 65px !important
    }
 
</style>
<div class="limiter" >
    <div class="container-login100" >
        <div class="wrap-login100" >
            <form class="login100-form validate-form">
                <span class="login100-form-title p-b-43">
                    Sign Up
                </span>


                <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input100" type="text" name="email" id="email-input">
                    <span class="focus-input100"></span>
                    <span class="label-input100">Email</span>
                </div>


                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="pass">
                    <span class="focus-input100"></span>
                    <span class="label-input100">Password</span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Password is required">
                    <input class="input100" type="password" name="pass">
                    <span class="focus-input100"></span>
                    <span class="label-input100">confirm password</span>
                </div>

                <div class="flex-sb-m w-full p-t-3 p-b-32">
                    <div class="contact100-form-checkbox">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                        <label class="label-checkbox100" for="ckb1">
                            Remember me
                        </label>
                    </div>

                    <div>
                        <a href="#" class="txt1">
                            Forgot Password?
                        </a>
                    </div>
                </div>


                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-46 p-b-20">
                    <span class="txt2">
                        or sign up using
                    </span>
                </div>

                <div class="login100-form-social flex-c-m">
                    <a href="#" class="login100-form-social-item flex-c-m bg1 m-r-5">
                        <i class="fa fa-facebook-f" aria-hidden="true"></i>
                    </a>

                    <a href="#" class="login100-form-social-item flex-c-m bg2 m-r-5">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
          

            <div class="login100-more" style="background-image:    url('@Url.Content("~/signup/images/signup.jpeg")');">

           .
            </div>
        </div>
    </div>
</div>





<!--===============================================================================================-->
<script src="~/signup/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/signup/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/signup/vendor/bootstrap/js/popper.js"></script>
<script src="~/signup/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/signup/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/signup/vendor/daterangepicker/moment.min.js"></script>
<script src="~/signup/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/signup/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/signup/js/main.js"></script>