ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Controllers/MajorsAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using University_Registration.Models;

namespace University_Registration.Controllers
{
    public class MajorsAdminController : Controller
    {
        private ERP_SystemEntities1 db = new ERP_SystemEntities1();
        [Authorize(Roles = "Admin")]

        // GET: MajorsAdmin
        public ActionResult Index()
        {

            var majors = db.Majors.Include(m => m.Facility);
            return View(majors.ToList());
        }
        [ActionName("Index")]
        [HttpPost]
        public ActionResult Index2(string search)
        {
            var majors = db.Majors.Where(p=>p.Name.Contains(search)).Include(m => m.Facility);
            return View(majors);
        }

        // GET: MajorsAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Major major = db.Majors.Find(id);
            if (major == null)
            {
                return HttpNotFound();
            }
            return View(major);
        }

        // GET: MajorsAdmin/Create
        public ActionResult Create()
        {
            ViewBag.Facility_ID = new SelectList(db.Facilities, "Facility_ID", "Name");
            return View();
        }

        // POST: MajorsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Major_ID,Name,Description,Major_Image,Facility_ID,price")] Major major, HttpPostedFileBase picture)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    try
                    {
                        string fileName = Path.GetFileName(picture.FileName);
                        string path = "~/Images/" + Path.GetFileName(picture.FileName);
                        string path2 = Path.GetFileName(picture.FileName);
                        picture.SaveAs(Server.MapPath(path));
                        major.Major_Image = path2.ToString();
                        Session["image"] = path2.ToString();
                        int flag = 0;
                        foreach (var item in db.Majors)
                        {

                            if (major.Name == item.Name)
                            {
                                ViewBag.alert = "You can not add the Major is alerady exist";
                                flag = 1;

                            }

                        }
                        if (flag == 0)
                        {
                            db.Majors.Add(major);
                            db.SaveChanges();
                            return RedirectToAction("Index");

                        }
                    }
                    catch (Exception ex)
                    {

                        major.Major_Image = Session["image"].ToString();
                        db.Majors.Add(major);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                }
                ViewBag.Facility_ID = new SelectList(db.Facilities, "Facility_ID", "Name", major.Facility_ID);
                return View(major);
            }
            catch(Exception ex) {
                ViewBag.alert = "You Must Upload the image";
                ViewBag.Facility_ID = new SelectList(db.Facilities, "Facility_ID", "Name", major.Facility_ID);
                return View(major);


            }
        }

        // GET: MajorsAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Major major = db.Majors.Find(id);
            if (major == null)
            {
                return HttpNotFound();
            }
            ViewBag.Facility_ID = new SelectList(db.Facilities, "Facility_ID", "Name", major.Facility_ID);
            return View(major);
        }

        // POST: MajorsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,[Bind(Include = "Major_ID,Name,Description,Major_Image,Facility_ID,price")] Major major, HttpPostedFileBase picture)
        {

            if (ModelState.IsValid)
            {
                var existingModel = db.Majors.AsNoTracking().FirstOrDefault(x => x.Major_ID == id);

                if (picture != null)
                {
                    string path = "~/Images/" + Path.GetFileName(picture.FileName);
                    picture.SaveAs(Server.MapPath(path));
                    major.Major_Image = picture.FileName;


                }
                else
                {
                    major.Major_Image= existingModel.Major_Image;
                }
                db.Entry(major).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Facility_ID = new SelectList(db.Facilities, "Facility_ID", "Name", major.Facility_ID);
            return View(major);
        }

        // GET: MajorsAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Major major = db.Majors.Find(id);
            if (major == null)
            {
                return HttpNotFound();
            }
            return View(major);
        }

        // POST: MajorsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Major major = db.Majors.Find(id);
                db.Majors.Remove(major);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception err) {
                return View("ErrorAdmin");

            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/MajorsAdmin/Create.cshtml
@model University_Registration.Models.Major

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Majors</a>

}

@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li class="active">
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li>
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}
<h1 style="color:red;">@ViewBag.alert</h1>
<style>
    tr td:first-child {
        padding: 1rem;
        width: 200px;
    }
</style>

@using (Html.BeginForm("Create", "MajorsAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })

            </td>
            <td>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                Major Image

            </td>
            <td>
                <input type="file" accept="image/*" name="picture" class="form-control" />
                @Html.ValidationMessageFor(model => model.Major_Image, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                Facility Name

            </td>
            <td>
                @Html.DropDownList("Facility_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Facility_ID, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                Price

            </td>
            <td>
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

        </div>
    </div>
}

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/MajorsAdmin/Delete.cshtml
@model University_Registration.Models.Major

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Majors</a>

}

@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li class="active">
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li>
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}


<style>
    tr td:first-child {
        padding: 1rem;
        width: 200px;
    }
</style>

<h3>Are you sure you want to delete this?</h3>


<table class="dl-horizontal">
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Name)
        </td>

        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Description)
        </td>

        <td>
            @Html.DisplayFor(model => model.Description)

        </td>
    </tr>
    <tr>


        <td>
            Price
        </td>

        <td>
            @Html.DisplayFor(model => model.price)
        </td>
    </tr>

    <tr>
        <td>
            Facility Name
        </td>

        <td>
            @Html.DisplayFor(model => model.Facility.Name)
        </td>
    </tr>
    <tr>
        <td>
            Major Image

        </td>
        <td>
            <img src="~/Images/@Model.Major_Image" style="width:100px;height:150px;" />
        </td>
    </tr>






</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
    </div>
}

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/MajorsAdmin/Details.cshtml
@model University_Registration.Models.Major

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}
@section header{

    <a href="#" class="nav-link">Majors</a>

}

@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li class="active">
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li>
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}


<style>
    tr td:first-child {
        padding: 1rem;
        width: 200px;
    }
</style>

<div>
    <dl class="dl-horizontal">
        <table>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Name)

                </td>
                <td>
                    @Html.DisplayFor(model => model.Name)

                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Description)

                </td>
                <td>
                    @Html.DisplayFor(model => model.Description)

                </td>
            </tr>

            </tr>
            <tr>
                <td>
                    Major Image
                </td>

                <td>
                    <img src="~/Images/@Model.Major_Image" style="width:60px;height:60px;" />
                </td>
            </tr>

            <tr>
                <td>
                    Price

                </td>
                <td>
                    @Html.DisplayFor(model => model.price)

                </td>
            </tr>
            <tr>
                <td>
                    Facility Name

                </td>
                <td>
                    @Html.DisplayFor(model => model.Facility.Name)

                </td>
            </tr>
        </table>







    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Major_ID }, new { @class = "btn btn-info" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/MajorsAdmin/Edit.cshtml
@model University_Registration.Models.Major

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Majors</a>

}

@section active{


    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li class="active">
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li>
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}

<style>
    tr td:first-child {
        padding: 1rem;
        width: 200px;
    }
</style>


@using (Html.BeginForm("Edit", "MajorsAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Major_ID)
        <table>
            <tr>
                <td>

                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                   Major Image

                </td>
                <td>
                    <img src="~/Images/@Model.Major_Image" style="width:60px;height:60px;" class="thumbnail" />

                    <input type="file" class="form-control" accept="image/*" name="picture" />
                    @Html.ValidationMessageFor(model => model.Major_Image, "", new { @class = "text-danger"})
                </td>
            </tr>
            <tr>
                <td>
                    Facility Name
                </td>
                <td>
                    @Html.DropDownList("Facility_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Facility_ID, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    Price

                </td>
                <td>
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </td>
            </tr>
        </table>






        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })

            </div>
        </div>
    </div>
}

ERB--main/ERB--main/ERP-Project-main/University_Registration/University_Registration/Views/MajorsAdmin/Index.cshtml
@model IEnumerable<University_Registration.Models.Major>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Adminlayout2.cshtml";
}

@section header{

    <a href="#" class="nav-link">Majors</a>

}

@section active{

    <ul class="side-menu top">
        <li>
            <a href="/FacilitiesAdmin/Index">
                <i class="fa-solid fa-building-columns"></i>
                <span class="text">Facilities</span>
            </a>
        </li>
        <li class="active">
            <a href="/MajorsAdmin/Index">
                <i class="fa-solid fa-graduation-cap"></i>
                <span class="text">Majors</span>
            </a>
        </li>

        <li>
            <a href="/SubjectsAdmin/Index">
                <i class="fa-solid fa-book"></i>
                <span class="text">Courses</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Index">
                <i class="fa-sharp fa-solid fa-users"></i>
                <span class="text">Students</span>
            </a>
        </li>

        <li>
            <a href="/StudentsAdmin/Acceptt">
                <i class="fa fa-check" aria-hidden="true"></i>
                <span class="text">Accept Student</span>
            </a>
        </li>
        <li>
            <a href="/StudentsAdmin/Rejectt">
                <i class="fa fa-ban" aria-hidden="true"></i>
                <span class="text">Reject Student</span>
            </a>
        </li>

        <li>
            <a href="/SubjectRegistrationsAdmin/Index">
                <i class="fa-solid fa-money-bill"></i>
                <span class="text">Payment</span>
            </a>
        </li>
        <li>
            <a href="/SubjectRegistrationsAdmin/Index2">
                <i class="fa-solid fa-dollar-sign"></i>
                <span class="text">Progress Payment</span>
            </a>
        </li>
        <li>
            <a href="/staticAdmin/Index">
                <i class="fas fa-chart-bar"></i>
                <span class="text">statistics </span>
            </a>
        </li>
    </ul>


}
<p style="width:8rem;margin-top:1%;margin-bottom:1%">
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info" })
</p>

@using (Html.BeginForm("Index2"))
{
    <div class="input-group justify-center">
        <div class="form-outline">
            <input type="search" id="form1" name="search" class="form-control" placeholder="Seach by Major Name" />
        </div>
        <input type="Submit" value="Search" class="btn btn-secondary" style="margin-bottom:1%" />
    </div>
}

<table class="table table-responsive table-striped table-hover ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Major Image
        </th>
        <th>
            Price
        </th>
        <th>
            Facility Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style="width:200px">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="~/Images/@item.Major_Image" style="width:60px;height:60px;" class="thumbnail" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Facility.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Major_ID }, new { @class = "btn btn-success" })
                @Html.ActionLink("Details", "Details", new { id = item.Major_ID }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Major_ID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>